 
import type { Metadata } from "next";
import { Encode_Sans_Expanded } from "next/font/google";
import Navbar from "./_components/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { Footer } from "./_components/Footer";
import "./globals.css";
import '../../node_modules/@fortawesome/fontawesome-free/css/all.css';
import NextAuthProvider from "@/providers/Components/nextauth.providers"; 
import Providers from "@/providers/Components/ReactQueryProvider.Provider";

const Encode = Encode_Sans_Expanded({
  subsets: ["latin"],
  weight:['300','400']
});


export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        
      <body  className={`${Encode.className} antialiased`}>
        <Providers>
          <Toaster  position="top-center" />
          <div className="flex flex-col justify-between items-center min-h-screen">
            <NextAuthProvider>
              <Navbar />
              {children}
              <Footer />
            </NextAuthProvider>
          </div>
        </Providers>
      </body>
    </html>
  );
}
